"""spoken_share package: D15 re-export of core spoken_share for scripts/core/smp/.

One implementation lives in ``core/spoken_share/spoken_share.py`` (manual L1);
this package re-exports it so ``import spoken_share`` under ``core/smp/`` keeps
resolving to the same rule (45% target, 40-55 band, every length and style,
rap counts as spoken, first real singing targeted at 15% of runtime). Skill 74 stays
the sole KIE path. Plan measuring and verification only — no network, no
spend. stdlib only.
"""
from .spoken_share import (  # noqa: F401
    CAP,
    DELIVERIES,
    BAND_ACCEPT,
    BAND_FLAG,
    BAND_REDO,
    FIRST_SUNG_TARGET_PCT,
    REAL_SINGING_STRETCH_S,
    TARGET_ACCEPT_PCT,
    TARGET_FLAG_PCT,
    FLOOR,
    SCHEMA_VERSION,
    SOURCE,
    SPOKEN_MAX_PCT,
    SPOKEN_MIN_PCT,
    SPOKEN_STYLE_DELIVERIES,
    SPOKEN_TARGET_PCT,
    TARGET,
    TOOL_NAME,
    TOOL_VERSION,
    SpokenShareError,
    band,
    check_first_sung,
    check_plan,
    check_share,
    is_spoken_style,
    judge_gap,
    measure_share,
    plan_refusal,
    refusal,
    seconds_for,
    segments_from_sung_stretches,
    share_pct,
    steer_first_sung,
)

__all__ = [
    "CAP",
    "DELIVERIES",
    "BAND_ACCEPT",
    "BAND_FLAG",
    "BAND_REDO",
    "FIRST_SUNG_TARGET_PCT",
    "REAL_SINGING_STRETCH_S",
    "TARGET_ACCEPT_PCT",
    "TARGET_FLAG_PCT",
    "FLOOR",
    "SCHEMA_VERSION",
    "SOURCE",
    "SPOKEN_MAX_PCT",
    "SPOKEN_MIN_PCT",
    "SPOKEN_STYLE_DELIVERIES",
    "SPOKEN_TARGET_PCT",
    "TARGET",
    "TOOL_NAME",
    "TOOL_VERSION",
    "SpokenShareError",
    "band",
    "check_first_sung",
    "check_plan",
    "check_share",
    "is_spoken_style",
    "judge_gap",
    "measure_share",
    "plan_refusal",
    "refusal",
    "seconds_for",
    "segments_from_sung_stretches",
    "share_pct",
    "steer_first_sung",
]
