#!/usr/bin/env python3
"""ONE RULESET: swarm-plan.mjs and staffing.py (and the packet's swarm_plan_check.py when SWARM_PLAN_CHECK_PY is set)
must accept and reject exactly the same plans. Fixtures are generated by `swarm-plan.mjs generate` with a capacity
fixture (so caps 10 and 6 are both exercised), then mutated."""
import copy, json, os, subprocess, sys, tempfile, unittest
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import plan_validators as pv

CAP = {10: {"ram_gb": 24, "cores": 12, "source": "fixture", "per_workflow_cap": 10, "max_working_agents": 500, "measured_at": "2026-01-01T00:00:00Z"},
       6: {"ram_gb": 9, "cores": 6, "source": "fixture", "per_workflow_cap": 6, "max_working_agents": 300, "measured_at": "2026-01-01T00:00:00Z"}}
WORDS = "alpha bravo charlie delta echo foxtrot golf hotel india juliet kilo lima mike november".split()


def breakdown(n_units_by_wf):
    wfs = []
    for wid, n in n_units_by_wf.items():
        wfs.append({"workflow_id": wid, "dependencies": [], "units": [
            {"work": "build the %s module %s" % (WORDS[k], WORDS[(k + 3) % len(WORDS)]), "owned_output": "src/%s/%s.py" % (wid, WORDS[k]),
             "acceptance": "tests for %s pass" % WORDS[k], "source": "SPEC 4"} for k in range(n)]})
    return {"workflows": wfs}


def dump(obj, path):
    with open(path, "w") as f:
        json.dump(obj, f)


def generate(cap, sizes):
    with tempfile.TemporaryDirectory() as d:
        dump(CAP[cap], os.path.join(d, "cap.json"))
        dump(breakdown(sizes), os.path.join(d, "b.json"))
        r = subprocess.run(["node", pv.MJS, "generate", d, os.path.join(d, "b.json"), "--capacity-fixture", os.path.join(d, "cap.json")], capture_output=True, text=True)
        assert r.returncode == 0, r.stderr
        with open(os.path.join(d, "SWARM-PLAN.json")) as f:
            return json.load(f)


class Agree(unittest.TestCase):
    def check(self, name, plan, want_ok):
        v = pv.verdicts(plan)
        got = {k: ok for k, (ok, _e) in v.items()}
        self.assertEqual(len(set(got.values())), 1, "%s: validators DISAGREE %s %s" % (name, got, {k: e[:2] for k, (_o, e) in v.items()}))
        self.assertEqual(next(iter(got.values())), want_ok, "%s: expected %s, got %s %s" % (name, "accept" if want_ok else "reject", got, v))

    def mut(self, plan, fn):
        p = copy.deepcopy(plan); fn(p); return p

    def test_agreement_cap10(self):
        base = generate(10, {"W1": 12, "W2": 3})
        self.check("generated plan, 12 units + 3 units", base, True)
        w = lambda p, i=0: p["workflows"][i]
        self.check("12 units agent_count 10 (cap)", base, True)
        self.assertEqual((w(base)["agent_count"], w(base, 1)["agent_count"]), (10, 3))
        self.check("agent_count != min(cap, units) (12 units, agent_count 12)", self.mut(base, lambda p: w(p).update(agent_count=12, concurrency=12)), False)
        self.check("agent_count 4 for 12 units", self.mut(base, lambda p: w(p).update(agent_count=4, concurrency=4)), False)
        self.check("concurrency != agent_count", self.mut(base, lambda p: w(p).update(concurrency=3)), False)
        self.check("duplicate owned_output", self.mut(base, lambda p: w(p)["units"][1].update(owned_output=w(p)["units"][0]["owned_output"])), False)
        self.check("owned_output directory accepted", self.mut(base, lambda p: w(p, 1)["units"][0].update(owned_output="docs/area/")), True)
        self.check("directory overlaps a file under it", self.mut(base, lambda p: w(p, 1)["units"][0].update(owned_output="src/W1/")), False)
        self.check("a/b vs a/bc.py do not overlap", self.mut(base, lambda p: (w(p, 1)["units"][0].update(owned_output="lib/b"), w(p, 1)["units"][1].update(owned_output="lib/bc.py"))), True)
        self.check("absolute owned_output", self.mut(base, lambda p: w(p)["units"][0].update(owned_output="/abs/x.py")), False)
        self.check("dotdot owned_output", self.mut(base, lambda p: w(p)["units"][0].update(owned_output="a/../x.py")), False)
        self.check("placeholder owned_output TBD", self.mut(base, lambda p: w(p)["units"][0].update(owned_output="src/TBD.py")), False)
        self.check("glob owned_output", self.mut(base, lambda p: w(p)["units"][0].update(owned_output="src/*.py")), False)
        self.check("padded: slice N of M", self.mut(base, lambda p: w(p)["units"][0].update(work="build slice 3 of 10 of it")), False)
        self.check("padded: identical work text", self.mut(base, lambda p: w(p)["units"][1].update(work=w(p)["units"][0]["work"])), False)
        self.check("padded: 12 units where 2 would do (same work, digits only differ)",
                   self.mut(base, lambda p: [u.update(work="do part %d" % i) for i, u in enumerate(w(p)["units"])]), False)
        self.check("plan status active (v2.1: only planned-not-running or running)", self.mut(base, lambda p: p.update(status="active")), False)
        self.check("plan status running accepted", self.mut(base, lambda p: p.update(status="running")), True)
        self.check("plan status missing", self.mut(base, lambda p: p.pop("status")), False)
        self.check("policy cap 11", self.mut(base, lambda p: p["policy"].update(max_agents_per_workflow=11)), False)
        self.check("policy cap missing", self.mut(base, lambda p: p["policy"].pop("max_agents_per_workflow")), False)
        self.check("max_working_agents 501", self.mut(base, lambda p: p["policy"].update(max_working_agents=501)), False)
        self.check("max_active_workflows 51", self.mut(base, lambda p: p["policy"].update(max_active_workflows=51)), False)
        for k in ("builders", "checkers", "repair_extra_executions_max", "max_total_executions"):
            self.check("leftover key " + k, self.mut(base, lambda p, k=k: w(p).update({k: 1})), False)
        self.check("bad unit verdict_file", self.mut(base, lambda p: w(p)["units"][0].update(verdict_file="evidence/x.json")), False)
        self.check("workflow-level verdict_file is a leftover key (contract v2.1)", self.mut(base, lambda p: w(p).update(verdict_file="evidence/W1/verdict.json")), False)
        self.check("dependency cycle", self.mut(base, lambda p: (w(p).update(dependencies=["W2"]), w(p, 1).update(dependencies=["W1"]))), False)
        self.check("unknown dependency", self.mut(base, lambda p: w(p).update(dependencies=["GHOST"])), False)

    def test_agreement_cap6(self):
        base = generate(6, {"W1": 8, "W2": 3})
        self.assertEqual(base["policy"]["max_agents_per_workflow"], 6)
        self.assertEqual(base["policy"]["max_working_agents"], 300)
        self.assertEqual([w["agent_count"] for w in base["workflows"]], [6, 3])  # 8 units -> agent_count 6
        self.check("cap-6 plan, 8 units -> agent_count 6", base, True)
        self.check("cap-6 plan with agent_count 8 (the old flat-10 rule)", self.mut(base, lambda p: p["workflows"][0].update(agent_count=8, concurrency=8)), False)
        self.check("cap hand-edited 6 -> 10 against its probe", self.mut(base, lambda p: p["policy"].update(max_agents_per_workflow=10)), False)
        self.check("cap hand-edited AND agent_counts follow (probe still says 6)",
                   self.mut(base, lambda p: (p["policy"].update(max_agents_per_workflow=10), p["workflows"][0].update(agent_count=8, concurrency=8))), False)
        self.check("cap 1 plan: agent_count 1 with probe cap 6", self.mut(base, lambda p: p["policy"].update(max_agents_per_workflow=1)), False)


if __name__ == "__main__":
    unittest.main(verbosity=2)
