#!/usr/bin/env python3
"""Independent FIX-004 determinism verification.

Contract:
- Runs the canonical build script TWICE into two clean, throwaway output
  directories (BUILD-A, BUILD-B) WITHOUT touching the committed derived/ tree.
  The build script's `--out-root` override writes to these temp dirs, so the
  committed DERIVATIVE-MANIFEST.json can be compared as a third, independent
  record.
- Build B runs in a deliberately different working directory with a different
  output root, proving no absolute-path or cwd dependence.
- Verifies: byte-identical derivative files across the two builds, identical
  manifest hashes and manifest text, integrity (sha256 of every file matches
  its record, dimensions match, sources listed, forbidden art checks:
  no upscale, alpha preserved, byte-size sane).
- Verifies the committed derived/ tree (generated by the builder) matches
  build A exactly, and that committed DERIVATIVE-MANIFEST.json matches build
  A's manifest.

Exit codes: 0 pass, 2 tool failure, 4 determinism/integrity failure.
"""

import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image

FIXED_MTIME = 1767225600


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def fail(msg: str, code: int) -> None:
    print(f"FAIL: {msg}", file=sys.stderr)
    sys.exit(code)


def rel_list(root: Path):
    out = []
    for p in sorted(root.rglob("*")):
        if p.is_file():
            out.append(str(p.relative_to(root)))
    return out


def mtimes(root: Path):
    bad = []
    for p in root.rglob("*"):
        if p.is_file() and int(p.stat().st_mtime) != FIXED_MTIME:
            bad.append(str(p.relative_to(root)))
    return bad


def run_build(build_script: Path, out_root: Path, cwd: Path) -> None:
    cmd = [sys.executable, str(build_script), "--out-root", str(out_root)]
    result = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        fail(f"build script failed with exit {result.returncode}", 2)


def manifest_load(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f"manifest unreadable: {path}: {exc}", 4)


def check_derivative(derived_root: Path, assets_root: Path, m, problems):
    for d in m["derivatives"]:
        p = derived_root / d["file"]
        if not p.exists():
            problems.append(f"missing file {d['file']}")
            continue
        if sha256_file(p) != d["sha256"]:
            problems.append(f"hash mismatch {d['file']}")
        if p.stat().st_size != d["bytes"]:
            problems.append(f"byte mismatch {d['file']}")
        if p.stat().st_mtime != FIXED_MTIME:
            problems.append(f"mtine not pinned {d['file']}")
        with Image.open(p) as im:
            if (im.width, im.height) != (d["width"], d["height"]):
                problems.append(f"dimension mismatch {d['file']}")
        for sid, ssum in zip(d["sourceIds"], d["sourceSha256"]):
            if not sid or not ssum:
                problems.append(f"source provenance missing on {d['file']}")
        # No upscale beyond native source dimensions. The tier's own target
        # box is a rendering constraint, not a size limit: the transform must
        # never exceed the native source dimensions.
        if d["transform"].get("crop") is None:
            # Whole-frame sources: native size comes from the source manifest,
            # read independently by this script, same as the builder does.
            sm = json.loads(
                (assets_root / "asset-manifest.json").read_text(encoding="utf-8")
            )
            src_entry = next(
                (a for a in sm["assets"] if a["id"] == d["sourceIds"][0]), None
            )
            if src_entry is None:
                problems.append(f"unknown source id {d['sourceIds'][0]}")
            else:
                if d["width"] > src_entry["width"] or d["height"] > src_entry["height"]:
                    problems.append(f"upscale beyond native {d['file']}")


def main() -> int:
    app_root = Path(__file__).resolve().parents[1]
    assets_root = app_root / "assets" / "candice"
    build_script = Path(__file__).resolve().parent / "build-derivatives.py"
    committed_derived = assets_root / "derived" / "approved-pending"
    committed_manifest = committed_derived / "DERIVATIVE-MANIFEST.json"

    if not build_script.exists():
        fail(f"build script missing: {build_script}", 2)

    with tempfile.TemporaryDirectory(prefix="candice-fix004-") as tmp:
        tmp_root = Path(tmp)
        out_a = tmp_root / "BUILD-A"
        out_b = tmp_root / "BUILD-B"

        print("Build A (worktree cwd)...")
        run_build(build_script, out_a, app_root)
        print("Build B (foreign cwd)...")
        run_build(build_script, out_b, tmp_root)  # different cwd on purpose

        man_a = manifest_load(out_a / "DERIVATIVE-MANIFEST.json")
        man_b = manifest_load(out_b / "DERIVATIVE-MANIFEST.json")

        files_a = rel_list(out_a)
        files_b = rel_list(out_b)
        if files_a != files_b:
            fail("file inventories differ between builds", 4)

        hashes_a = {f: sha256_file(out_a / f) for f in files_a}
        hashes_b = {f: sha256_file(out_b / f) for f in files_b}
        differing = [f for f in files_a if hashes_a[f] != hashes_b[f]]
        if differing:
            fail(f"byte differences across builds: {differing}", 4)

        text_a = (out_a / "DERIVATIVE-MANIFEST.json").read_text(encoding="utf-8")
        text_b = (out_b / "DERIVATIVE-MANIFEST.json").read_text(encoding="utf-8")
        if text_a != text_b:
            fail("manifest text differs across builds", 4)

        bad_m = mtimes(out_a)
        if bad_m:
            fail(f"unpinned mtimes: {bad_m}", 4)

        # Integrity of build A's records.
        problems = []
        check_derivative(out_a, assets_root, man_a, problems)
        if problems:
            fail("integrity problems: " + "; ".join(problems[:20]), 4)

        if man_a.get("derivativeCount") != len(man_a["derivatives"]):
            fail("derivativeCount disagrees with record list", 4)

        # Committed tree must match build A exactly.
        if not committed_manifest.exists():
            fail("committed DERIVATIVE-MANIFEST.json missing; run the builder first", 2)
        if rel_list(committed_derived) != files_a:
            fail("committed derived/ tree differs from fresh build inventory", 4)
        for f in files_a:
            if sha256_file(committed_derived / f) != hashes_a[f]:
                fail(f"committed file differs from fresh build: {f}", 4)
        if committed_manifest.read_text(encoding="utf-8") != text_a:
            fail("committed DERIVATIVE-MANIFEST.json differs from fresh build", 4)

        n = len(man_a["derivatives"])
        total = sum(d["bytes"] for d in man_a["derivatives"])
        print(
            f"VERIFY PASS: two independent builds byte-identical "
            f"({n} derivatives, {total} bytes); committed tree matches; "
            f"mtimes pinned; hashes pinned."
        )
        return 0


if __name__ == "__main__":
    sys.exit(main())
